In [0]:
import pandas as pd
import numpy as np

In [0]:
data = pd.read_csv('pima-indians-diabetes.csv')

In [65]:
data

6  148  72  35    0  33.6  0.627  50  1
0     1   85  66  29    0  26.6  0.351  31  0
1     8  183  64   0    0  23.3  0.672  32  1
2     1   89  66  23   94  28.1  0.167  21  0
3     0  137  40  35  168  43.1  2.288  33  1
4     5  116  74   0    0  25.6  0.201  30  0
5     3   78  50  32   88  31.0  0.248  26  1
6    10  115   0   0    0  35.3  0.134  29  0
7     2  197  70  45  543  30.5  0.158  53  1
8     8  125  96   0    0   0.0  0.232  54  1
9     4  110  92   0    0  37.6  0.191  30  0
10   10  168  74   0    0  38.0  0.537  34  1
11   10  139  80   0    0  27.1  1.441  57  0
12    1  189  60  23  846  30.1  0.398  59  1
13    5  166  72  19  175  25.8  0.587  51  1
14    7  100   0   0    0  30.0  0.484  32  1
15    0  118  84  47  230  45.8  0.551  31  1
16    7  107  74   0    0  29.6  0.254  31  1
17    1  103  30  38   83  43.3  0.183  33  0
18    1  115  70  30   96  34.6  0.529  32  1
19    3  126  88  41  235  39.3  0.704  27  0
20    8   99  84   0    0  35.4  0.388  50  0
21    7  196  90   0    0  39.8  0.451  41  1
22    9  119  80  35    0  29.0  0.263  29  1
23   11  143  94  33  146  36.6  0.254  51  1
24   10  125  70  26  115  31.1  0.205  41  1
25    7  147  76   0    0  39.4  0.257  43  1
26    1   97  66  15  140  23.2  0.487  22  0
27   13  145  82  19  110  22.2  0.245  57  0
28    5  117  92   0    0  34.1  0.337  38  0
29    5  109  75  26    0  36.0  0.546  60  0
..   ..  ...  ..  ..  ...   ...    ...  .. ..
737   2   99  60  17  160  36.6  0.453  21  0
738   1  102  74   0    0  39.5  0.293  42  1
739  11  120  80  37  150  42.3  0.785  48  1
740   3  102  44  20   94  30.8  0.400  26  0
741   1  109  58  18  116  28.5  0.219  22  0
742   9  140  94   0    0  32.7  0.734  45  1
743  13  153  88  37  140  40.6  1.174  39  0
744  12  100  84  33  105  30.0  0.488  46  0
745   1  147  94  41    0  49.3  0.358  27  1
746   1   81  74  41   57  46.3  1.096  32  0
747   3  187  70  22  200  36.4  0.408  36  1
748   6  162  62   0    0  24.3  0.178  50  1
749   4  136  70   0    0  31.2  1.182  22  1
750   1  121  78  39   74  39.0  0.261  28  0
751   3  108  62  24    0  26.0  0.223  25  0
752   0  181  88  44  510  43.3  0.222  26  1
753   8  154  78  32    0  32.4  0.443  45  1
754   1  128  88  39  110  36.5  1.057  37  1
755   7  137  90  41    0  32.0  0.391  39  0
756   0  123  72   0    0  36.3  0.258  52  1
757   1  106  76   0    0  37.5  0.197  26  0
758   6  190  92   0    0  35.5  0.278  66  1
759   2   88  58  26   16  28.4  0.766  22  0
760   9  170  74  31    0  44.0  0.403  43  1
761   9   89  62   0    0  22.5  0.142  33  0
762  10  101  76  48  180  32.9  0.171  63  0
763   2  122  70  27    0  36.8  0.340  27  0
764   5  121  72  23  112  26.2  0.245  30  0
765   1  126  60   0    0  30.1  0.349  47  1
766   1   93  70  31    0  30.4  0.315  23  0

[767 rows x 9 columns]

In [66]:
data = data.values
data

array([[1.00e+00, 8.50e+01, 6.60e+01, ..., 3.51e-01, 3.10e+01, 0.00e+00],
       [8.00e+00, 1.83e+02, 6.40e+01, ..., 6.72e-01, 3.20e+01, 1.00e+00],
       [1.00e+00, 8.90e+01, 6.60e+01, ..., 1.67e-01, 2.10e+01, 0.00e+00],
       ...,
       [5.00e+00, 1.21e+02, 7.20e+01, ..., 2.45e-01, 3.00e+01, 0.00e+00],
       [1.00e+00, 1.26e+02, 6.00e+01, ..., 3.49e-01, 4.70e+01, 1.00e+00],
       [1.00e+00, 9.30e+01, 7.00e+01, ..., 3.15e-01, 2.30e+01, 0.00e+00]])

In [67]:
x = data[:,0:8].astype(float)

from sklearn import preprocessing

min_max_scaler = preprocessing.MinMaxScaler()
x_scaled = min_max_scaler.fit_transform(x)
print(x_scaled)

x_train = x_scaled[0:540]
x_test = x_scaled[541:760]

[[0.05882353 0.42713568 0.54098361 ... 0.39642325 0.11656704 0.16666667]
 [0.47058824 0.91959799 0.52459016 ... 0.34724292 0.25362938 0.18333333]
 [0.05882353 0.44723618 0.54098361 ... 0.41877794 0.03800171 0.        ]
 ...
 [0.29411765 0.6080402  0.59016393 ... 0.390462   0.07130658 0.15      ]
 [0.05882353 0.63316583 0.49180328 ... 0.4485842  0.11571307 0.43333333]
 [0.05882353 0.46733668 0.57377049 ... 0.45305514 0.10119556 0.03333333]]


In [68]:
y = data[:,8]
print(y)
y_train = y[0:540]
y_test = y[541:760]

[0. 1. 0. 1. 0. 1. 0. 1. 1. 0. 1. 0. 1. 1. 1. 1. 1. 0. 1. 0. 0. 1. 1. 1.
 1. 1. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 1. 1. 1. 0. 0. 0. 1. 0. 1. 0. 0. 1.
 0. 0. 0. 0. 1. 0. 0. 1. 0. 0. 0. 0. 1. 0. 0. 1. 0. 1. 0. 0. 0. 1. 0. 1.
 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 1. 0. 0. 0. 1. 0. 0. 0. 0. 1. 0. 0. 0.
 0. 0. 1. 1. 0. 0. 0. 0. 0. 0. 0. 0. 1. 1. 1. 0. 0. 1. 1. 1. 0. 0. 0. 1.
 0. 0. 0. 1. 1. 0. 0. 1. 1. 1. 1. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0.
 0. 0. 0. 0. 0. 0. 0. 1. 0. 1. 1. 0. 0. 0. 1. 0. 0. 0. 0. 1. 1. 0. 0. 0.
 0. 1. 1. 0. 0. 0. 1. 0. 1. 0. 1. 0. 0. 0. 0. 0. 1. 1. 1. 1. 1. 0. 0. 1.
 1. 0. 1. 0. 1. 1. 1. 0. 0. 0. 0. 0. 0. 1. 1. 0. 1. 0. 0. 0. 1. 1. 1. 1.
 0. 1. 1. 1. 1. 0. 0. 0. 0. 0. 1. 0. 0. 1. 1. 0. 0. 0. 1. 1. 1. 1. 0. 0.
 0. 1. 1. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 1. 1. 0. 0. 0. 1. 0. 1. 0. 0. 1.
 0. 1. 0. 0. 1. 1. 0. 0. 0. 0. 0. 1. 0. 0. 0. 1. 0. 0. 1. 1. 0. 0. 1. 0.
 0. 0. 1. 1. 1. 0. 0. 1. 0. 1. 0. 1. 1. 0. 1. 0. 0. 1. 0. 1. 1. 0. 0. 1.
 0. 1. 0. 0. 1. 0. 1. 0. 1. 1. 1. 0. 0. 1. 0. 1. 0.

In [69]:
len(x_train)

540

In [70]:
len(x_test)

219

In [0]:
from keras import models
from keras import layers

In [0]:
network = models.Sequential()
network.add(layers.Dense(12, activation='relu', input_dim=8))
network.add(layers.Dense(10, activation='relu'))
network.add(layers.Dense(8, activation='relu'))
network.add(layers.Dense(4, activation='relu'))
network.add(layers.Dense(1, activation='sigmoid'))

In [0]:
network.compile(optimizer='rmsprop',
                loss='binary_crossentropy',
                metrics=['accuracy'])

In [74]:
network.fit(x_train, y_train, validation_split=0.3, shuffle=True, epochs=70, batch_size=10)

Train on 378 samples, validate on 162 samples
Epoch 1/70
378/378 [==============================] - 1s 1ms/step - loss: 0.6865 - acc: 0.6164 - val_loss: 0.6688 - val_acc: 0.7160
Epoch 2/70
378/378 [==============================] - 0s 629us/step - loss: 0.6790 - acc: 0.6190 - val_loss: 0.6573 - val_acc: 0.7160
Epoch 3/70
378/378 [==============================] - 0s 606us/step - loss: 0.6746 - acc: 0.6190 - val_loss: 0.6471 - val_acc: 0.7160
Epoch 4/70
378/378 [==============================] - 0s 610us/step - loss: 0.6714 - acc: 0.6190 - val_loss: 0.6399 - val_acc: 0.7160
Epoch 5/70
378/378 [==============================] - 0s 606us/step - loss: 0.6693 - acc: 0.6190 - val_loss: 0.6363 - val_acc: 0.7160
Epoch 6/70
378/378 [==============================] - 0s 599us/step - loss: 0.6673 - acc: 0.6190 - val_loss: 0.6327 - val_acc: 0.7160
Epoch 7/70
378/378 [==============================] - 0s 604us/step - loss: 0.6658 - acc: 0.6190 - val_loss: 0.6310 - val_acc: 0.7160
Epoch 8/70
378/378

378/378 [==============================] - 0s 723us/step - loss: 0.6298 - acc: 0.6190 - val_loss: 0.5886 - val_acc: 0.7160
Epoch 17/70
378/378 [==============================] - 0s 722us/step - loss: 0.6241 - acc: 0.6190 - val_loss: 0.5798 - val_acc: 0.7160
Epoch 18/70
378/378 [==============================] - 0s 722us/step - loss: 0.6179 - acc: 0.6243 - val_loss: 0.5796 - val_acc: 0.7284
Epoch 19/70
378/378 [==============================] - 0s 717us/step - loss: 0.6118 - acc: 0.6614 - val_loss: 0.5684 - val_acc: 0.7346
Epoch 20/70
378/378 [==============================] - 0s 724us/step - loss: 0.6045 - acc: 0.6693 - val_loss: 0.5602 - val_acc: 0.7469
Epoch 21/70
378/378 [==============================] - 0s 722us/step - loss: 0.5988 - acc: 0.6905 - val_loss: 0.5654 - val_acc: 0.7407
Epoch 22/70
378/378 [==============================] - 0s 720us/step - loss: 0.5903 - acc: 0.6693 - val_loss: 0.5668 - val_acc: 0.7160
Epoch 23/70
378/378 [==============================] - 0s 733us/ste

378/378 [==============================] - 0s 741us/step - loss: 0.5506 - acc: 0.7037 - val_loss: 0.5285 - val_acc: 0.7284
Epoch 32/70
378/378 [==============================] - 0s 731us/step - loss: 0.5475 - acc: 0.7063 - val_loss: 0.5147 - val_acc: 0.7407
Epoch 33/70
378/378 [==============================] - 0s 746us/step - loss: 0.5437 - acc: 0.7275 - val_loss: 0.5251 - val_acc: 0.7222
Epoch 34/70
378/378 [==============================] - 0s 737us/step - loss: 0.5408 - acc: 0.7275 - val_loss: 0.5056 - val_acc: 0.7593
Epoch 35/70
378/378 [==============================] - 0s 743us/step - loss: 0.5397 - acc: 0.7143 - val_loss: 0.5217 - val_acc: 0.7222
Epoch 36/70
378/378 [==============================] - 0s 731us/step - loss: 0.5347 - acc: 0.7249 - val_loss: 0.5014 - val_acc: 0.7593
Epoch 37/70
378/378 [==============================] - 0s 723us/step - loss: 0.5370 - acc: 0.7196 - val_loss: 0.5061 - val_acc: 0.7469
Epoch 38/70
378/378 [==============================] - 0s 736us/ste

378/378 [==============================] - 0s 745us/step - loss: 0.5196 - acc: 0.7169 - val_loss: 0.4893 - val_acc: 0.7654
Epoch 47/70
378/378 [==============================] - 0s 744us/step - loss: 0.5196 - acc: 0.7328 - val_loss: 0.5002 - val_acc: 0.7593
Epoch 48/70
378/378 [==============================] - 0s 726us/step - loss: 0.5188 - acc: 0.7302 - val_loss: 0.4860 - val_acc: 0.7716
Epoch 49/70
378/378 [==============================] - 0s 752us/step - loss: 0.5114 - acc: 0.7434 - val_loss: 0.4861 - val_acc: 0.7716
Epoch 50/70
378/378 [==============================] - 0s 736us/step - loss: 0.5144 - acc: 0.7460 - val_loss: 0.4779 - val_acc: 0.7716
Epoch 51/70
378/378 [==============================] - 0s 717us/step - loss: 0.5155 - acc: 0.7434 - val_loss: 0.4763 - val_acc: 0.7716
Epoch 52/70
378/378 [==============================] - 0s 736us/step - loss: 0.5104 - acc: 0.7540 - val_loss: 0.4976 - val_acc: 0.7531
Epoch 53/70
378/378 [==============================] - 0s 730us/ste

378/378 [==============================] - 0s 752us/step - loss: 0.5050 - acc: 0.7407 - val_loss: 0.4669 - val_acc: 0.7901
Epoch 62/70
378/378 [==============================] - 0s 719us/step - loss: 0.5034 - acc: 0.7540 - val_loss: 0.4726 - val_acc: 0.8025
Epoch 63/70
378/378 [==============================] - 0s 750us/step - loss: 0.4991 - acc: 0.7593 - val_loss: 0.4658 - val_acc: 0.7901
Epoch 64/70
378/378 [==============================] - 0s 757us/step - loss: 0.5006 - acc: 0.7672 - val_loss: 0.4707 - val_acc: 0.7963
Epoch 65/70
378/378 [==============================] - 0s 749us/step - loss: 0.5047 - acc: 0.7566 - val_loss: 0.4731 - val_acc: 0.7840
Epoch 66/70
378/378 [==============================] - 0s 736us/step - loss: 0.5004 - acc: 0.7487 - val_loss: 0.4655 - val_acc: 0.8025
Epoch 67/70
378/378 [==============================] - 0s 746us/step - loss: 0.5000 - acc: 0.7487 - val_loss: 0.4728 - val_acc: 0.7840
Epoch 68/70
378/378 [==============================] - 0s 745us/ste

In [75]:

network.evaluate(x_test, y_test)

219/219 [==============================] - 0s 107us/step


[0.44692620784724685, 0.7899543349057028]

In [76]:
vectors_answers = network.predict(x_test[210:])
vectors_answers = np.where(vectors_answers > 0.5, 1, 0)
print(vectors_answers)

[[0]
 [0]
 [1]
 [0]
 [0]
 [0]
 [0]
 [1]
 [0]]
