In [0]:
import pandas as pd
import numpy as np

In [0]:
# from google.colab import files
# up = files.upload()

In [84]:
data = pd.read_csv('winequality-white.csv', delimiter=';')
data.head()

fixed acidity  volatile acidity  citric acid  residual sugar  chlorides  \
0            7.0              0.27         0.36            20.7      0.045   
1            6.3              0.30         0.34             1.6      0.049   
2            8.1              0.28         0.40             6.9      0.050   
3            7.2              0.23         0.32             8.5      0.058   
4            7.2              0.23         0.32             8.5      0.058   

   free sulfur dioxide  total sulfur dioxide  density    pH  sulphates  \
0                 45.0                 170.0   1.0010  3.00       0.45   
1                 14.0                 132.0   0.9940  3.30       0.49   
2                 30.0                  97.0   0.9951  3.26       0.44   
3                 47.0                 186.0   0.9956  3.19       0.40   
4                 47.0                 186.0   0.9956  3.19       0.40   

   alcohol  quality  
0      8.8        6  
1      9.5        6  
2     10.1        6  
3      9.9        6  
4      9.9        6

In [85]:
data.describe()

fixed acidity  volatile acidity  citric acid  residual sugar  \
count    4898.000000       4898.000000  4898.000000     4898.000000   
mean        6.854788          0.278241     0.334192        6.391415   
std         0.843868          0.100795     0.121020        5.072058   
min         3.800000          0.080000     0.000000        0.600000   
25%         6.300000          0.210000     0.270000        1.700000   
50%         6.800000          0.260000     0.320000        5.200000   
75%         7.300000          0.320000     0.390000        9.900000   
max        14.200000          1.100000     1.660000       65.800000   

         chlorides  free sulfur dioxide  total sulfur dioxide      density  \
count  4898.000000          4898.000000           4898.000000  4898.000000   
mean      0.045772            35.308085            138.360657     0.994027   
std       0.021848            17.007137             42.498065     0.002991   
min       0.009000             2.000000              9.000000     0.987110   
25%       0.036000            23.000000            108.000000     0.991723   
50%       0.043000            34.000000            134.000000     0.993740   
75%       0.050000            46.000000            167.000000     0.996100   
max       0.346000           289.000000            440.000000     1.038980   

                pH    sulphates      alcohol      quality  
count  4898.000000  4898.000000  4898.000000  4898.000000  
mean      3.188267     0.489847    10.514267     5.877909  
std       0.151001     0.114126     1.230621     0.885639  
min       2.720000     0.220000     8.000000     3.000000  
25%       3.090000     0.410000     9.500000     5.000000  
50%       3.180000     0.470000    10.400000     6.000000  
75%       3.280000     0.550000    11.400000     6.000000  
max       3.820000     1.080000    14.200000     9.000000

In [86]:
# Separating Data
x = data.values[:,0:11]
print(len(x))

from sklearn import preprocessing

min_max_scaler = preprocessing.MinMaxScaler()
x = min_max_scaler.fit_transform(x)
print(x)

# Total Of 4898 Rows
# --------------------
# Train Data
train_data = x[0:3000]
print(len(train_data))

# Test Data
test_data = x[3000:]
print(len(test_data))

4898
[[0.30769231 0.18627451 0.21686747 ... 0.25454545 0.26744186 0.12903226]
 [0.24038462 0.21568627 0.20481928 ... 0.52727273 0.31395349 0.24193548]
 [0.41346154 0.19607843 0.24096386 ... 0.49090909 0.25581395 0.33870968]
 ...
 [0.25961538 0.15686275 0.11445783 ... 0.24545455 0.27906977 0.22580645]
 [0.16346154 0.20588235 0.18072289 ... 0.56363636 0.18604651 0.77419355]
 [0.21153846 0.12745098 0.22891566 ... 0.49090909 0.11627907 0.61290323]]
3000
1898


In [87]:
# Separating Labels
y = data.values[:,11]
print(y.shape)

# Total Of 4898 Rows
# --------------------
# Train Data
# print(train_label.shape)
# Test Data
# print(test_label.shape)

(4898,)


In [88]:
from keras.utils import to_categorical

y = to_categorical(y)
print(y.shape)

print(train_label.shape)
print(test_label.shape)

train_label = y[0:3000]

test_label = y[3000:]


(4898, 10)
(3000, 10)
(1898, 10)


In [0]:
from keras import models
from keras import layers

In [0]:
def baseline_model():
  network = models.Sequential()
  network.add(layers.Dense(11, activation='relu', input_dim=11))
  network.add(layers.Dense(15, activation='relu'))
  # network.add(layers.Dense(8, activation='relu'))
  # network.add(layers.Dense(4, activation='relu'))
  network.add(layers.Dense(10, activation='softmax'))
  network.compile(optimizer='rmsprop',
                loss='categorical_crossentropy',
                metrics=['accuracy'])
  return network

In [108]:
from keras.wrappers.scikit_learn import KerasClassifier
from keras.utils import np_utils
from sklearn.model_selection import cross_val_score
from sklearn.model_selection import KFoldhttps://lh3.googleusercontent.com/a/default-user=s128
from sklearn.preprocessing import LabelEncoder
from sklearn.pipeline import Pipeline

estimator = KerasClassifier(build_fn=baseline_model, epochs=100, batch_size=10, verbose=2)

kfold = KFold(n_splits=5, shuffle=True)

results = cross_val_score(estimator, test_data, test_label, cv=kfold)
print("Baseline: %.2f%% (%.2f%%)" % (results.mean()*100, results.std()*100))



Epoch 1/100
 - 2s - loss: 1.7929 - acc: 0.3775
Epoch 2/100
 - 1s - loss: 1.2545 - acc: 0.5040
Epoch 3/100
 - 1s - loss: 1.1960 - acc: 0.5040
Epoch 4/100
 - 1s - loss: 1.1682 - acc: 0.5046
Epoch 5/100
 - 1s - loss: 1.1476 - acc: 0.5079
Epoch 6/100
 - 1s - loss: 1.1320 - acc: 0.5257
Epoch 7/100
 - 1s - loss: 1.1208 - acc: 0.5343
Epoch 8/100
 - 1s - loss: 1.1096 - acc: 0.5428
Epoch 9/100
 - 1s - loss: 1.1062 - acc: 0.5520
Epoch 10/100
 - 1s - loss: 1.0997 - acc: 0.5567
Epoch 11/100
 - 1s - loss: 1.0924 - acc: 0.5580
Epoch 12/100
 - 1s - loss: 1.0893 - acc: 0.5619
Epoch 13/100
 - 1s - loss: 1.0862 - acc: 0.5632
Epoch 14/100
 - 1s - loss: 1.0788 - acc: 0.5580
Epoch 15/100
 - 1s - loss: 1.0774 - acc: 0.5619
Epoch 16/100
 - 1s - loss: 1.0753 - acc: 0.5632
Epoch 17/100
 - 1s - loss: 1.0690 - acc: 0.5777
Epoch 18/100
 - 1s - loss: 1.0670 - acc: 0.5685
Epoch 19/100
 - 1s - loss: 1.0658 - acc: 0.5692
Epoch 20/100
 - 1s - loss: 1.0631 - acc: 0.5777
Epoch 21/100
 - 1s - loss: 1.0597 - acc: 0.5797
E

 - 1s - loss: 1.0272 - acc: 0.5791
Epoch 47/100
 - 1s - loss: 1.0270 - acc: 0.5843
Epoch 48/100
 - 1s - loss: 1.0265 - acc: 0.5823
Epoch 49/100
 - 1s - loss: 1.0240 - acc: 0.5889
Epoch 50/100
 - 1s - loss: 1.0252 - acc: 0.5856
Epoch 51/100
 - 1s - loss: 1.0242 - acc: 0.5843
Epoch 52/100
 - 1s - loss: 1.0223 - acc: 0.5830
Epoch 53/100
 - 1s - loss: 1.0216 - acc: 0.5863
Epoch 54/100
 - 1s - loss: 1.0195 - acc: 0.5896
Epoch 55/100
 - 1s - loss: 1.0197 - acc: 0.5876
Epoch 56/100
 - 1s - loss: 1.0189 - acc: 0.5856
Epoch 57/100
 - 1s - loss: 1.0190 - acc: 0.5889
Epoch 58/100
 - 1s - loss: 1.0174 - acc: 0.5883
Epoch 59/100
 - 1s - loss: 1.0171 - acc: 0.5922
Epoch 60/100
 - 1s - loss: 1.0167 - acc: 0.5804
Epoch 61/100
 - 1s - loss: 1.0138 - acc: 0.5837
Epoch 62/100
 - 1s - loss: 1.0150 - acc: 0.5870
Epoch 63/100
 - 1s - loss: 1.0144 - acc: 0.5837
Epoch 64/100
 - 1s - loss: 1.0156 - acc: 0.5863
Epoch 65/100
 - 1s - loss: 1.0128 - acc: 0.5889
Epoch 66/100
 - 1s - loss: 1.0120 - acc: 0.5850
Epoch

 - 1s - loss: 0.9922 - acc: 0.5876
Epoch 92/100
 - 1s - loss: 0.9905 - acc: 0.5909
Epoch 93/100
 - 1s - loss: 0.9933 - acc: 0.5870
Epoch 94/100
 - 1s - loss: 0.9911 - acc: 0.5922
Epoch 95/100
 - 1s - loss: 0.9913 - acc: 0.5870
Epoch 96/100
 - 1s - loss: 0.9893 - acc: 0.5962
Epoch 97/100
 - 1s - loss: 0.9886 - acc: 0.5870
Epoch 98/100
 - 1s - loss: 0.9888 - acc: 0.5968
Epoch 99/100
 - 1s - loss: 0.9871 - acc: 0.5942
Epoch 100/100
 - 1s - loss: 0.9868 - acc: 0.5876
Epoch 1/100
 - 2s - loss: 1.8840 - acc: 0.4447
Epoch 2/100
 - 1s - loss: 1.2595 - acc: 0.5053
Epoch 3/100
 - 1s - loss: 1.1942 - acc: 0.5059
Epoch 4/100
 - 1s - loss: 1.1704 - acc: 0.5066
Epoch 5/100
 - 1s - loss: 1.1471 - acc: 0.5171
Epoch 6/100
 - 1s - loss: 1.1274 - acc: 0.5428
Epoch 7/100
 - 1s - loss: 1.1095 - acc: 0.5501
Epoch 8/100
 - 1s - loss: 1.0968 - acc: 0.5639
Epoch 9/100
 - 1s - loss: 1.0876 - acc: 0.5685
Epoch 10/100
 - 1s - loss: 1.0791 - acc: 0.5692
Epoch 11/100
 - 1s - loss: 1.0698 - acc: 0.5804
Epoch 12/100


 - 1s - loss: 0.9974 - acc: 0.6014
Epoch 37/100
 - 1s - loss: 0.9964 - acc: 0.6074
Epoch 38/100
 - 1s - loss: 0.9954 - acc: 0.6041
Epoch 39/100
 - 1s - loss: 0.9951 - acc: 0.6140
Epoch 40/100
 - 1s - loss: 0.9933 - acc: 0.6113
Epoch 41/100
 - 1s - loss: 0.9923 - acc: 0.6008
Epoch 42/100
 - 1s - loss: 0.9906 - acc: 0.6153
Epoch 43/100
 - 1s - loss: 0.9908 - acc: 0.6107
Epoch 44/100
 - 1s - loss: 0.9896 - acc: 0.6054
Epoch 45/100
 - 1s - loss: 0.9875 - acc: 0.6113
Epoch 46/100
 - 1s - loss: 0.9871 - acc: 0.6094
Epoch 47/100
 - 1s - loss: 0.9854 - acc: 0.6094
Epoch 48/100
 - 1s - loss: 0.9866 - acc: 0.6087
Epoch 49/100
 - 1s - loss: 0.9835 - acc: 0.6100
Epoch 50/100
 - 1s - loss: 0.9819 - acc: 0.6061
Epoch 51/100
 - 1s - loss: 0.9820 - acc: 0.6094
Epoch 52/100
 - 1s - loss: 0.9809 - acc: 0.6080
Epoch 53/100
 - 1s - loss: 0.9814 - acc: 0.6140
Epoch 54/100
 - 1s - loss: 0.9776 - acc: 0.6153
Epoch 55/100
 - 1s - loss: 0.9791 - acc: 0.6153
Epoch 56/100
 - 1s - loss: 0.9782 - acc: 0.6140
Epoch

 - 1s - loss: 0.9564 - acc: 0.6179
Epoch 82/100
 - 1s - loss: 0.9565 - acc: 0.6179
Epoch 83/100
 - 1s - loss: 0.9572 - acc: 0.6120
Epoch 84/100
 - 1s - loss: 0.9553 - acc: 0.6166
Epoch 85/100
 - 1s - loss: 0.9565 - acc: 0.6199
Epoch 86/100
 - 1s - loss: 0.9558 - acc: 0.6186
Epoch 87/100
 - 1s - loss: 0.9556 - acc: 0.6074
Epoch 88/100
 - 1s - loss: 0.9542 - acc: 0.6166
Epoch 89/100
 - 1s - loss: 0.9532 - acc: 0.6219
Epoch 90/100
 - 1s - loss: 0.9499 - acc: 0.6206
Epoch 91/100
 - 1s - loss: 0.9524 - acc: 0.6212
Epoch 92/100
 - 1s - loss: 0.9496 - acc: 0.6192
Epoch 93/100
 - 1s - loss: 0.9490 - acc: 0.6199
Epoch 94/100
 - 1s - loss: 0.9491 - acc: 0.6258
Epoch 95/100
 - 1s - loss: 0.9490 - acc: 0.6186
Epoch 96/100
 - 1s - loss: 0.9477 - acc: 0.6140
Epoch 97/100
 - 1s - loss: 0.9476 - acc: 0.6159
Epoch 98/100
 - 1s - loss: 0.9440 - acc: 0.6252
Epoch 99/100
 - 1s - loss: 0.9448 - acc: 0.6252
Epoch 100/100
 - 1s - loss: 0.9454 - acc: 0.6159
Epoch 1/100
 - 2s - loss: 1.6177 - acc: 0.4493
Epoch

 - 1s - loss: 1.0288 - acc: 0.5843
Epoch 27/100
 - 1s - loss: 1.0283 - acc: 0.5797
Epoch 28/100
 - 1s - loss: 1.0243 - acc: 0.5843
Epoch 29/100
 - 1s - loss: 1.0247 - acc: 0.5777
Epoch 30/100
 - 1s - loss: 1.0220 - acc: 0.5955
Epoch 31/100
 - 1s - loss: 1.0223 - acc: 0.5916
Epoch 32/100
 - 1s - loss: 1.0223 - acc: 0.5909
Epoch 33/100
 - 1s - loss: 1.0195 - acc: 0.5955
Epoch 34/100
 - 1s - loss: 1.0190 - acc: 0.5863
Epoch 35/100
 - 1s - loss: 1.0188 - acc: 0.5896
Epoch 36/100
 - 1s - loss: 1.0175 - acc: 0.5896
Epoch 37/100
 - 1s - loss: 1.0174 - acc: 0.5949
Epoch 38/100
 - 1s - loss: 1.0161 - acc: 0.5896
Epoch 39/100
 - 1s - loss: 1.0160 - acc: 0.5870
Epoch 40/100
 - 1s - loss: 1.0147 - acc: 0.5922
Epoch 41/100
 - 1s - loss: 1.0139 - acc: 0.5889
Epoch 42/100
 - 1s - loss: 1.0144 - acc: 0.5935
Epoch 43/100
 - 1s - loss: 1.0132 - acc: 0.5922
Epoch 44/100
 - 1s - loss: 1.0115 - acc: 0.5903
Epoch 45/100
 - 1s - loss: 1.0113 - acc: 0.5883
Epoch 46/100
 - 1s - loss: 1.0120 - acc: 0.5909
Epoch

 - 1s - loss: 0.9942 - acc: 0.5975
Epoch 72/100
 - 1s - loss: 0.9961 - acc: 0.5975
Epoch 73/100
 - 1s - loss: 0.9941 - acc: 0.6008
Epoch 74/100
 - 1s - loss: 0.9934 - acc: 0.5975
Epoch 75/100
 - 1s - loss: 0.9955 - acc: 0.6061
Epoch 76/100
 - 1s - loss: 0.9937 - acc: 0.6014
Epoch 77/100
 - 1s - loss: 0.9910 - acc: 0.6087
Epoch 78/100
 - 1s - loss: 0.9934 - acc: 0.5995
Epoch 79/100
 - 1s - loss: 0.9921 - acc: 0.6008
Epoch 80/100
 - 1s - loss: 0.9921 - acc: 0.6014
Epoch 81/100
 - 1s - loss: 0.9917 - acc: 0.6001
Epoch 82/100
 - 1s - loss: 0.9919 - acc: 0.6001
Epoch 83/100
 - 1s - loss: 0.9894 - acc: 0.6014
Epoch 84/100
 - 1s - loss: 0.9907 - acc: 0.5975
Epoch 85/100
 - 1s - loss: 0.9900 - acc: 0.5949
Epoch 86/100
 - 1s - loss: 0.9895 - acc: 0.5975
Epoch 87/100
 - 1s - loss: 0.9880 - acc: 0.5968
Epoch 88/100
 - 1s - loss: 0.9883 - acc: 0.6021
Epoch 89/100
 - 1s - loss: 0.9887 - acc: 0.5995
Epoch 90/100
 - 1s - loss: 0.9872 - acc: 0.5962
Epoch 91/100
 - 1s - loss: 0.9866 - acc: 0.6008
Epoch

 - 1s - loss: 1.0584 - acc: 0.5787
Epoch 17/100
 - 1s - loss: 1.0523 - acc: 0.5767
Epoch 18/100
 - 1s - loss: 1.0510 - acc: 0.5780
Epoch 19/100
 - 1s - loss: 1.0465 - acc: 0.5747
Epoch 20/100
 - 1s - loss: 1.0444 - acc: 0.5833
Epoch 21/100
 - 1s - loss: 1.0407 - acc: 0.5800
Epoch 22/100
 - 1s - loss: 1.0381 - acc: 0.5747
Epoch 23/100
 - 1s - loss: 1.0347 - acc: 0.5872
Epoch 24/100
 - 1s - loss: 1.0331 - acc: 0.5846
Epoch 25/100
 - 1s - loss: 1.0311 - acc: 0.5846
Epoch 26/100
 - 1s - loss: 1.0286 - acc: 0.5912
Epoch 27/100
 - 1s - loss: 1.0252 - acc: 0.5879
Epoch 28/100
 - 1s - loss: 1.0247 - acc: 0.5839
Epoch 29/100
 - 1s - loss: 1.0239 - acc: 0.5866
Epoch 30/100
 - 1s - loss: 1.0217 - acc: 0.5879
Epoch 31/100
 - 1s - loss: 1.0195 - acc: 0.5905
Epoch 32/100
 - 1s - loss: 1.0139 - acc: 0.5899
Epoch 33/100
 - 1s - loss: 1.0149 - acc: 0.5905
Epoch 34/100
 - 1s - loss: 1.0143 - acc: 0.5826
Epoch 35/100
 - 1s - loss: 1.0104 - acc: 0.5885
Epoch 36/100
 - 1s - loss: 1.0109 - acc: 0.5899
Epoch

 - 1s - loss: 0.9759 - acc: 0.5918
Epoch 62/100
 - 1s - loss: 0.9753 - acc: 0.5971
Epoch 63/100
 - 1s - loss: 0.9743 - acc: 0.5991
Epoch 64/100
 - 1s - loss: 0.9732 - acc: 0.5984
Epoch 65/100
 - 1s - loss: 0.9727 - acc: 0.6057
Epoch 66/100
 - 1s - loss: 0.9704 - acc: 0.5964
Epoch 67/100
 - 1s - loss: 0.9703 - acc: 0.5925
Epoch 68/100
 - 1s - loss: 0.9697 - acc: 0.6057
Epoch 69/100
 - 1s - loss: 0.9667 - acc: 0.5938
Epoch 70/100
 - 1s - loss: 0.9665 - acc: 0.5997
Epoch 71/100
 - 1s - loss: 0.9673 - acc: 0.5945
Epoch 72/100
 - 1s - loss: 0.9659 - acc: 0.5945
Epoch 73/100
 - 1s - loss: 0.9647 - acc: 0.5978
Epoch 74/100
 - 1s - loss: 0.9642 - acc: 0.6017
Epoch 75/100
 - 1s - loss: 0.9625 - acc: 0.6011
Epoch 76/100
 - 1s - loss: 0.9636 - acc: 0.5991
Epoch 77/100
 - 1s - loss: 0.9628 - acc: 0.5971
Epoch 78/100
 - 1s - loss: 0.9613 - acc: 0.5991
Epoch 79/100
 - 1s - loss: 0.9585 - acc: 0.6037
Epoch 80/100
 - 1s - loss: 0.9607 - acc: 0.5958
Epoch 81/100
 - 1s - loss: 0.9571 - acc: 0.6004
Epoch

 - 1s - loss: 1.1800 - acc: 0.4937
Epoch 7/100
 - 1s - loss: 1.1633 - acc: 0.4951
Epoch 8/100
 - 1s - loss: 1.1476 - acc: 0.4951
Epoch 9/100
 - 1s - loss: 1.1344 - acc: 0.5010
Epoch 10/100
 - 1s - loss: 1.1250 - acc: 0.5016
Epoch 11/100
 - 1s - loss: 1.1181 - acc: 0.4970
Epoch 12/100
 - 1s - loss: 1.1105 - acc: 0.5115
Epoch 13/100
 - 1s - loss: 1.1054 - acc: 0.5326
Epoch 14/100
 - 1s - loss: 1.1007 - acc: 0.5260
Epoch 15/100
 - 1s - loss: 1.0956 - acc: 0.5458
Epoch 16/100
 - 1s - loss: 1.0912 - acc: 0.5398
Epoch 17/100
 - 1s - loss: 1.0884 - acc: 0.5458
Epoch 18/100
 - 1s - loss: 1.0845 - acc: 0.5438
Epoch 19/100
 - 1s - loss: 1.0815 - acc: 0.5523
Epoch 20/100
 - 1s - loss: 1.0770 - acc: 0.5497
Epoch 21/100
 - 1s - loss: 1.0736 - acc: 0.5543
Epoch 22/100
 - 1s - loss: 1.0727 - acc: 0.5543
Epoch 23/100
 - 1s - loss: 1.0697 - acc: 0.5589
Epoch 24/100
 - 1s - loss: 1.0678 - acc: 0.5569
Epoch 25/100
 - 1s - loss: 1.0657 - acc: 0.5550
Epoch 26/100
 - 1s - loss: 1.0625 - acc: 0.5648
Epoch 27

 - 1s - loss: 1.0233 - acc: 0.5872
Epoch 52/100
 - 1s - loss: 1.0212 - acc: 0.5826
Epoch 53/100
 - 1s - loss: 1.0193 - acc: 0.5872
Epoch 54/100
 - 1s - loss: 1.0204 - acc: 0.5833
Epoch 55/100
 - 1s - loss: 1.0189 - acc: 0.5859
Epoch 56/100
 - 1s - loss: 1.0169 - acc: 0.5879
Epoch 57/100
 - 1s - loss: 1.0165 - acc: 0.5945
Epoch 58/100
 - 1s - loss: 1.0151 - acc: 0.5885
Epoch 59/100
 - 1s - loss: 1.0156 - acc: 0.5866
Epoch 60/100
 - 1s - loss: 1.0127 - acc: 0.5951
Epoch 61/100
 - 1s - loss: 1.0147 - acc: 0.5958
Epoch 62/100
 - 1s - loss: 1.0128 - acc: 0.5820
Epoch 63/100
 - 1s - loss: 1.0118 - acc: 0.5892
Epoch 64/100
 - 1s - loss: 1.0092 - acc: 0.5905
Epoch 65/100
 - 1s - loss: 1.0104 - acc: 0.5938
Epoch 66/100
 - 1s - loss: 1.0086 - acc: 0.5892
Epoch 67/100
 - 1s - loss: 1.0083 - acc: 0.5866
Epoch 68/100
 - 1s - loss: 1.0070 - acc: 0.5833
Epoch 69/100
 - 1s - loss: 1.0048 - acc: 0.5899
Epoch 70/100
 - 1s - loss: 1.0033 - acc: 0.5892
Epoch 71/100
 - 1s - loss: 1.0036 - acc: 0.5839
Epoch

 - 1s - loss: 0.9810 - acc: 0.5938
Epoch 97/100
 - 1s - loss: 0.9816 - acc: 0.5885
Epoch 98/100
 - 1s - loss: 0.9797 - acc: 0.5879
Epoch 99/100
 - 1s - loss: 0.9782 - acc: 0.5925
Epoch 100/100
 - 1s - loss: 0.9784 - acc: 0.5932
Baseline: 59.54% (3.10%)


In [109]:
network.evaluate(test_data, test_label)

1898/1898 [==============================] - 1s 353us/step


[1.1199205296685246, 0.5021074815595363]